"use strict"

module.exports = {
  url: "https://developer-diary.netlify.com",
  title: "DJ's Developer Diary",
  tagline: " Lead DevOps Engineer and Kubernetes Specialist",
  copyright: "© 2019 dj, All rights reserved",
  author: {
    name: "Dixon Joseph Dalmeida",
    bio: "Senior DevOps Engineer",
    contacts: {
      linkedin: "https://www.linkedin.com/in/dj-dixon-joseph-d-almeida-4443a7a3",
      github: "https://github.com/starlord-dixon",
      stackoverflow:
        "https://stackoverflow.com/users/7256390/dixon-almeida?tab=profile",
      linktree: "https://linktr.ee/Dj_DixonJoseph",
      twitter: "https://twitter.com/DixonAlmeida",
    },
  },
  labels: [
    {
      tag: "devops",
      tech: "DevOps",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "kubernetes",
      tech: "Kubernetes",
      name: "DiCssTricks",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "docker",
      tech: "Docker",
      name: "FaDocker",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "jenkins",
      tech: "Jenkins",
      name: "FaJenkins",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "spinnaker",
      tech: "Spinnaker",
      name: "DiRuby",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "aws",
      tech: "AWS",
      name: "FaAmazon",
      size: 20,
      color: "wheat",
    },
    {
      tag: "azure",
      tech: "Azure",
      name: "FaMicrosoft",
      size: 20,
      color: "red",
    },
    {
      tag: "monitoring",
      tech: "Monitoring",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "golang",
      tech: "golang",
      name: "FaGithubAlt",
      size: 20,
      color: "violet",
    },
    {
      tag: "linux",
      tech: "Linux",
      name: "FaLinux",
      size: 20,
      color: "green",
    },
    {
      tag: "helm",
      tech: "Helm",
      name: "DiCssTricks",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
