"use strict"

module.exports = {
  url: "https://developer-diary.netlify.com",
  title: "DJ's Developer Diary",
  tagline: "Kubernetes Specialist",
  copyright: "© 2019 dj, All rights reserved",
  author: {
    name: "Dixon Joseph Dalmeida",
    bio: "Senior DevOps Engineer",
    contacts: {
      linkedin: "https://www.linkedin.com/in/dj-dixon-joseph-d-almeida-4443a7a3",
      github: "https://github.com/willjw3",
      stackoverflow:
        "https://stackoverflow.com/users/10262432/will-ward?tab=profile",
      freecodecamp: "https://linktr.ee/Dj_DixonJoseph",
      twitter: "https://twitter.com/willjw3",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "DevOps",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Kubernetes",
      name: "DiCssTricks",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "Jenkins",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "Jenkins",
      name: "FaJenkins",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Spinnaker",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "AWS",
      name: "FaAmazon",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Azure",
      name: "FaMicrosoft",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "Monitoring",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
